In [1]:
#Problem01

import numpy as np  
sigmax=np.array([[0,1],[1,0]])  
print(sigmax)  
eigenvalues, eigenvectors = np.linalg.eig(sigmax)  
print(eigenvalues)  
print(eigenvectors) 

[[0 1]
 [1 0]]
[ 1.+0.j -1.+0.j]
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]


In [ ]:
#Problem04-1

import numpy as np

# Pauli matrices
sx = np.array([
    [0, 1],
    [1, 0]
])

sz = np.array([
    [1, 0],
    [0, -1]
])

# Find eigenvalues and eigenvectors of sigma_x
eigenvalues, eigenvectors = np.linalg.eig(sx)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 1.+0.j -1.+0.j]

Eigenvectors:
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]


In [3]:
#Problem04-2
up = np.array([1, 0])
down = np.array([0, 1])

P_up = np.dot(
    up.reshape(2, 1),
    np.transpose(up.reshape(2, 1))
)

P_down = np.dot(
    down.reshape(2, 1),
    np.transpose(down.reshape(2, 1))
)

print("P_up:")
print(P_up)

print("\nP_down:")
print(P_down)

P_up:
[[1 0]
 [0 0]]

P_down:
[[0 0]
 [0 1]]


In [4]:
#Problem04-3
for i in range(2):

    psi = eigenvectors[:, i]

    # <psi| P_up |psi>
    p_up = np.dot(
        np.transpose(psi),
        np.dot(P_up, psi)
    )

    # <psi| P_down |psi>
    p_down = np.dot(
        np.transpose(psi),
        np.dot(P_down, psi)
    )

    print(f"\nEigenstate {i+1}")
    print("Probability of spin up:  ", p_up)
    print("Probability of spin down:", p_down)


Eigenstate 1
Probability of spin up:   (0.4999999999999999+0j)
Probability of spin down: (0.4999999999999999+0j)

Eigenstate 2
Probability of spin up:   (0.4999999999999999+0j)
Probability of spin down: (0.4999999999999999+0j)


In [7]:
#Problem07

import numpy as np  

#Determinant of sigmax
M=np.array([[0,1], [1,0]])  
print("Determinant of sigmax:", np.linalg.det(M)) 

#Determinant of sigmay
M=np.array([[0,-1j], [1j,0]])
print("Determinant of sigmay:", np.linalg.det(M))

#Determinant of sigmaz
M=np.array([[1,0], [0,-1]])
print("Determinant of sigmaz:", np.linalg.det(M))


Determinant of sigmax: -1.0
Determinant of sigmay: (-1+0j)
Determinant of sigmaz: -1.0
